#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pg.Dataverse.Model
{
	
	
	/// <summary>
	/// Type of entity with which the activity attachment is associated.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "1.0.0.24")]
	public enum activityfileattachment_objectcode
	{
		
		/// <summary>
		/// Post
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Post = 8000,
		
		/// <summary>
		/// Post Comment
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PostComment = 8005,
	}
}
#pragma warning restore CS1591
