#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pg.Dataverse.Model
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "1.0.0.24")]
	public enum adx_likertscaleagreement
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		StronglyDisagree = 100000000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Disagree = 100000001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Undecided = 100000002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Agree = 100000003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		StronglyAgree = 100000004,
	}
}
#pragma warning restore CS1591
