#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pg.Dataverse.Model
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "1.0.0.24")]
	public enum connectortype
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CustomConnector = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NotSpecified = 0,
	}
}
#pragma warning restore CS1591
