#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pg.Dataverse.Model
{
	
	
	/// <summary>
	/// Type of channel activities.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "1.0.0.24")]
	public enum convertrule_channelactivity
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PhoneCall = 4210,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Email = 4202,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Appointment = 4201,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Task = 4212,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SocialActivity = 4216,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AlertSubscription = 10241,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InviteRedemption = 10244,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PortalComment = 10293,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ActivityrecordfortheTeamschat = 10307,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CustomerVoicealert = 10537,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CustomerVoicesurveyinvite = 10547,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CustomerVoicesurveyresponse = 10549,
	}
}
#pragma warning restore CS1591
