#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pg.Dataverse.Model
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "1.0.0.24")]
	public enum pg_scoring
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Low = 554390000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Medium = 554390001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		High = 554390002,
	}
}
#pragma warning restore CS1591
